### ISSUE TITLE
Make it work again

### ISSUE THREAD

**Issue by BartMassey** [BartMassey/PlayRustClassifier#1]
- Remove rustc_serialize
- Remove features like custom_derive/plugin
- Update to latest serde, which works on stable
- Vendor in rsml or whatever bits we use https://docs.rs/rsml/0.1.0/rsml/
- Move to 2018 edition

**Comment by BartMassey** [comment]
Copied from insanitybit/PlayRustClassifier#3

**Comment by bitemyapp** [comment]
I didn't see your comment before I wrote this PR, maybe it'll help you on this issue: https://github.com/insanitybit/PlayRustClassifier/pull/4

I have the app building with mostly current dependencies except `rand`. I haven't tried running it though.

**Comment by BartMassey** [comment]
Sigh. Sorry to put you through duplicate work. :frown: I reviewed the changes in your PR and it looks like most of them are on `main` here.

Yeah, getting `rand` updated involved also rewriting the `rustlearn` crate to modern. You can find that [here](/BartMassey-upstream/rustlearn).

**Comment by BartMassey** [comment]
Closed by 6883d99 and its predecessors.
